{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a2z-insurance.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a2z-insurance.labels" . | nindent 4 }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}
